export const ADMIN_USERS_GET_REQUEST = "ADMIN_USERS_GET_REQUEST"
export const ADMIN_USERS_GET_SUCCESS = "ADMIN_USERS_GET_SUCCESS"
export const ADMIN_USERS_GET_FAIL = "ADMIN_USERS_GET_FAIL"


export const ADMIN_FOODS_GET_REQUEST = "ADMIN_FOODS_GET_REQUEST"
export const ADMIN_FOODS_GET_SUCCESS = "ADMIN_FOODS_GET_SUCCESS"
export const ADMIN_FOODS_GET_FAIL = "ADMIN_FOODS_GET_FAIL"


export const ADMIN_ORDERS_GET_REQUEST = "ADMIN_ORDERS_GET_REQUEST"
export const ADMIN_ORDERS_GET_SUCCESS = "ADMIN_ORDERS_GET_SUCCESS"
export const ADMIN_ORDERS_GET_FAIL = "ADMIN_ORDERS_GET_FAIL"




export const CLEAR_ADMIN_ERROR = "CLEAR_ADMIN_ERROR"