export const GET_ALL_REVIEW_REQUEST = 'GET_ALL_REVIEW_REQUEST'
export const GET_ALL_REVIEW_SUCCESS = 'GET_ALL_REVIEW_SUCCESS'
export const GET_ALL_REVIEW_FAIL = 'GET_ALL_REVIEW_FAIL'

export const USER_GET_REVIEW_REQUEST = 'USER_GET_REVIEW_REQUEST'
export const USER_GET_REVIEW_SUCCESS = 'USER_GET_REVIEW_SUCCESS'
export const USER_GET_REVIEW_FAIL = 'USER_GET_REVIEW_FAIL'

export const USER_CREATE_REVIEW_REQUEST = 'USER_CREATE_REVIEW_REQUEST'
export const USER_CREATE_REVIEW_SUCCESS = 'USER_CREATE_REVIEW_SUCCESS'
export const USER_CREATE_REVIEW_FAIL = 'USER_CREATE_REVIEW_FAIL'
export const USER_CREATE_REVIEW_RESET = "USER_CREATE_REVIEW_RESET"






export const CLEAR_REVIEW_ERROR = "CLEAR_REVIEW_ERROR"