export const GET_ALL_FOOD_REQUEST = "GET_ALL_FOOD_REQUEST"
export const GET_ALL_FOOD_SUCCESS = "GET_ALL_FOOD_SUCCESS"
export const GET_ALL_FOOD_FAIL = "GET_ALL_FOOD_FAIL"

export const GET_SINGLE_FOOD_REQUEST = "GET_SINGLE_FOOD_REQUEST"
export const GET_SINGLE_FOOD_SUCCESS = "GET_SINGLE_FOOD_SUCCESS"
export const GET_SINGLE_FOOD_FAIL = "GET_SINGLE_FOOD_FAIL"


export const CLEAR_ERROR = "CLEAR_ERROR"