export const USER_ORDER_REQUEST = 'USER_ORDER_REQUEST'
export const USER_ORDER_SUCCESS = 'USER_ORDER_SUCCESS'
export const USER_ORDER_FAIL = 'USER_ORDER_FAIL'

export const USER_ORDERS_GET_REQUEST = 'USER_ORDERS_GET_REQUEST'
export const USER_ORDERS_GET_SUCCESS = 'USER_ORDERS_GET_SUCCESS'
export const USER_ORDERS_GET_FAIL = 'USER_ORDERS_GET_FAIL'



export const ORDER_CREATED_RESET = 'ORDER_CREATED_RESET'
export const CLEAR_ORDER_ERROR = 'CLEAR_ORDER_ERROR'